server:
  port: 10086
  address: 0.0.0.0
  servlet:
    context-path: /icm/

spring:
  profiles:
    active: development-local
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect    #默认使用innodb引擎
      hibernate.format_sql: true
      hibernate.max_fetch_depth: 1
      hibernate.generate_statistics: true
      hibernate.use_sql_comments: false

zj:
  kamixiya:
    upload:
      # fileType上传时拦截的文件类型，
      file-filter-type: .jsp.asp.exe
      # flag 上传文件时临时保存的路径
      temp-path: ${java.io.tmpdir}${file.separator}files${file.separator}
      #  filePath 上传时的文件保存路径
      file-path: ${user.dir}${file.separator}files${file.separator}
      # 预览文件临时存放路径
      temp-dir-files: ${java.io.tmpdir}
    preview:
      # 预览时转换后的文件类型
      file-type: .pdf
    snowflake:
      idc: 1
      machine: 1

---
spring:
  profiles: development-aliyun
  datasource:
    name: MYDB
    #    data: classpath:/sql/data-mysql.sql
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.31.172.101:3306/icm?serverTimezone=Hongkong&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=false&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 123456
  #    initialization-mode: always

---
spring:
  profiles: development-local
  datasource:
    name: MYDB
    #    data: classpath:/sql/data-mysql.sql
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/icm?serverTimezone=Hongkong&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=false&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: root
  #    initialization-mode: always